# cloudbuild.yaml
steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/pubsub-puller:$COMMIT_SHA', '.']

  # Step 2: Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/pubsub-puller:$COMMIT_SHA']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'pubsub-puller-service' # Name of your Cloud Run service
      - '--image=gcr.io/$PROJECT_ID/pubsub-puller:$COMMIT_SHA'
      - '--region=us-central1' # Choose your desired region (e.g., us-central1, europe-west1)
      - '--platform=managed'
      - '--allow-unauthenticated' # Allow unauthenticated access (for easy testing)
      # --- TEMPORARY CHANGE HERE: HARDCODE SUBSCRIPTION ID FOR DEBUGGING ---
      - '--set-env-vars=GOOGLE_CLOUD_PROJECT=$PROJECT_ID,PUBSUB_SUBSCRIPTION_ID=my-first-test-1595-sub'
      # --- END OF TEMPORARY CHANGE ---
      - '--port=8080' # Ensure the port matches your application (Flask default is 8080)
    env:
      - 'CLOUDSDK_CORE_DISABLE_PROMPTS=1' # Disable prompts for non-interactive execution

images:
  - 'gcr.io/$PROJECT_ID/pubsub-puller:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY

# IMPORTANT: Remove or comment out the 'substitutions' block at the end if you
# are solely relying on this hardcoded value for testing this specific problem.
# If you leave the substitution in the Cloud Build trigger, it *might* override
# this, but usually the --set-env-vars takes precedence.
