steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/pubsub-puller:$COMMIT_SHA', '.']

  # Step 2: Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/pubsub-puller:$COMMIT_SHA']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'pubsub-puller-service' # Cloud Run service name
      - '--image=gcr.io/$PROJECT_ID/pubsub-puller:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-env-vars=GCP_PROJECT_ID=$PROJECT_ID,PUBSUB_SUBSCRIPTION_ID=my-first-test-1595-sub'
      - '--port=8080'
      - '--quiet'

images:
  - 'gcr.io/$PROJECT_ID/pubsub-puller:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
