steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['builds', 'submit', '--tag', 'gcr.io/your-gcp-project-id/pubsub-puller']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'pubsub-puller',
           '--image', 'gcr.io/your-gcp-project-id/pubsub-puller',
           '--platform', 'managed',
           '--region', 'us-central1',
           '--allow-unauthenticated']
